# Generated by Django 5.0.4 on 2024-05-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('pep8_compliant', models.BooleanField(default=False)),
                ('flake8_compliant', models.BooleanField(default=False)),
            ],
        ),
    ]
