# Generated by Django 5.0.4 on 2024-05-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkedfile',
            name='flake8_compliant',
        ),
    ]
